#!/usr/bin/env python3
"""
install-to-claude.py

Sync wiki-template's slash commands + subagents vào ~/.claude/ và setup
~/.claude/wiki-global.json với wiki_root trỏ về repo này.

Idempotent: re-run mỗi khi pull wiki-template mới để cập nhật.
Không động vào commands/agents user tự tạo (chỉ sync file đến từ wiki-template).

Usage:
  python scripts/install-to-claude.py [WIKI_ROOT] [--dry-run] [--force]

  WIKI_ROOT  Đường dẫn tuyệt đối đến wiki-template repo (default: parent
             của script này, tức là repo root khi chạy từ scripts/).
  --dry-run  In ra những gì sẽ làm, KHÔNG copy/ghi file.
  --force    Skip confirmation khi overwrite ~/.claude/wiki-global.json.
"""

import argparse
import filecmp
import json
import os
import re
import shutil
import sys
from pathlib import Path


def resolve_wiki_root(arg: str | None) -> Path:
    if arg:
        p = Path(arg).resolve()
    else:
        p = Path(__file__).resolve().parent.parent
    return p


def validate_wiki_root(wiki_root: Path) -> None:
    if not wiki_root.is_dir():
        print(f"✗ WIKI_ROOT không tồn tại: {wiki_root}", file=sys.stderr)
        sys.exit(1)
    if not (wiki_root / ".claude" / "commands").is_dir() or not (wiki_root / "agents").is_dir():
        print(
            f"✗ {wiki_root} không phải wiki-template repo (thiếu .claude/commands/ hoặc agents/).",
            file=sys.stderr,
        )
        sys.exit(1)


def sync_file(src: Path, dst: Path, label: str, dry_run: bool) -> None:
    if not dst.exists():
        print(f"  [NEW]       {label}")
        if not dry_run:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
    elif not filecmp.cmp(src, dst, shallow=False):
        print(f"  [UPDATED]   {label}")
        if not dry_run:
            shutil.copy2(src, dst)
    else:
        print(f"  [UNCHANGED] {label}")


def sync_dir(src_dir: Path, dst_dir: Path, label: str, dry_run: bool) -> None:
    print(f"── {label} → {dst_dir}")
    if not dry_run:
        dst_dir.mkdir(parents=True, exist_ok=True)

    md_files = sorted(src_dir.glob("*.md"))
    for src in md_files:
        sync_file(src, dst_dir / src.name, src.name, dry_run)
    print()


def handle_global_config(wiki_root: Path, global_config: Path, force: bool, dry_run: bool) -> None:
    print(f"── Global config → {global_config}")

    # JSON dùng forward slash để portable trên mọi OS
    wiki_root_fwd = wiki_root.as_posix()

    new_config = {
        "_comment": (
            "Generated by wiki-template/scripts/install-to-claude.py. "
            "wiki_root trỏ về wiki-template repo. "
            "Edit default_workspace nếu muốn fallback cho codebase chưa có .claude/wiki.json."
        ),
        "wiki_root": wiki_root_fwd,
        "default_workspace": None,
        "default_domain": None,
    }

    if not global_config.exists():
        print(f"  [NEW] {global_config}")
        if not dry_run:
            global_config.parent.mkdir(parents=True, exist_ok=True)
            global_config.write_text(
                json.dumps(new_config, ensure_ascii=False, indent=2), encoding="utf-8"
            )
    else:
        # Đọc wiki_root hiện tại
        try:
            existing = json.loads(global_config.read_text(encoding="utf-8"))
            current_root = existing.get("wiki_root", "")
        except (json.JSONDecodeError, OSError):
            current_root = ""

        if current_root == wiki_root_fwd:
            print(f"  [UNCHANGED] wiki_root đã đúng ({wiki_root_fwd})")
        else:
            print(f"  [CONFLICT] wiki_root hiện tại: {current_root or '<empty>'}")
            print(f"             wiki_root mới     : {wiki_root_fwd}")
            if force:
                print("  [FORCED]    overwrite (--force)")
                if not dry_run:
                    global_config.write_text(
                        json.dumps(new_config, ensure_ascii=False, indent=2), encoding="utf-8"
                    )
            else:
                print()
                print("  ⚠ Không tự overwrite (sẽ mất default_workspace/default_domain user đã set).")
                print(f"    Để overwrite hoàn toàn:  python {__file__} {wiki_root} --force")
                print(f"    Hoặc edit thủ công:      {global_config}")
    print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sync wiki-template vào ~/.claude/ (Windows-compatible)",
        add_help=True,
    )
    parser.add_argument("wiki_root", nargs="?", default=None, help="Đường dẫn tới wiki-template repo")
    parser.add_argument("--dry-run", action="store_true", help="In ra kế hoạch, không thực thi")
    parser.add_argument("--force", action="store_true", help="Overwrite wiki-global.json kể cả khi xung đột")
    args = parser.parse_args()

    wiki_root = resolve_wiki_root(args.wiki_root)
    validate_wiki_root(wiki_root)

    global_claude = Path.home() / ".claude"
    global_commands = global_claude / "commands"
    global_agents = global_claude / "agents"
    global_config = global_claude / "wiki-global.json"

    print(f"Wiki root:  {wiki_root}")
    print(f"Global dir: {global_claude}")
    if args.dry_run:
        print("Mode:       DRY RUN (no changes)")
    print()

    # 1. Slash commands
    sync_dir(
        wiki_root / ".claude" / "commands",
        global_commands,
        "Slash commands",
        args.dry_run,
    )

    # 2. Subagents
    sync_dir(
        wiki_root / ".claude" / "agents",
        global_agents,
        "Subagents",
        args.dry_run,
    )

    # 3. wiki-global.json
    handle_global_config(wiki_root, global_config, args.force, args.dry_run)

    print("✓ Done.")
    print()
    print("Test thử:")
    print("  cd /path/to/your/codebase")
    print("  /wiki-setup           # tạo .claude/wiki.json cho codebase đó")
    print("  /list-workspaces      # xem có workspace nào trong wiki-template")
    print('  /use-wiki "...task..."  # dùng pipeline với context từ workspace active')


if __name__ == "__main__":
    main()
